Traceback (most recent call last):
  File "/opt/anaconda3/envs/jupyter-book-py311/lib/python3.11/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/opt/anaconda3/envs/jupyter-book-py311/lib/python3.11/site-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/jupyter-book-py311/lib/python3.11/site-packages/jupyter_core/utils/__init__.py", line 173, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/jupyter-book-py311/lib/python3.11/asyncio/base_events.py", line 654, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/jupyter-book-py311/lib/python3.11/site-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/opt/anaconda3/envs/jupyter-book-py311/lib/python3.11/site-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/opt/anaconda3/envs/jupyter-book-py311/lib/python3.11/site-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
my_text="Melos is a naive young shepherd with a sense of justice. He lives in a land ruled by Dionysius, a tyrant king who has killed many people, including his family members, due to his solitude and distrust of people. When Melos hears about the King's deeds, he is outraged, and he decides to assassinate the King. He sneaks into the castle with a knife but is caught and arrested. Although Melos defiantly owns up to his plan to kill the King, he pleads with the cynical tyrant to postpone his execution for three days so that he can return home to arrange his younger sister's marriage. As collateral for his pledge to return, Melos offers his friend Selinuntius as a hostage, who would be executed in his stead should Melos not return in time. The King agrees to Melos' conditions but threatens to kill him should he return moments too late. Melos insists that saving his own life is not his intention. Informed of the situation, Selinuntius readily agrees to the role that Melos assigned him without asking."
inputs=my_text.replace(' ', '').replace('\'', '').replace(',', '').strip().upper()[:306]

import matplotlib.pyplot as plt

# 暗号画像を生成する
img = np.ones((1050-17*22,420,3),np.uint8)*255
b,g,r,a = 0,0,0,0
# フォントを読み込む
fontpath = "/Library/Fonts/z340-z408.ttf"
font = ImageFont.truetype(fontpath, 32)
img_pil = Image.fromarray(img)
draw = ImageDraw.Draw(img_pil)
h=100 # 文字を描き始める最初の高さ
for i in fullfontcode.split("\n"):
	draw.text((50, h), i.strip(), font = font, fill = (b, g, r, a))
	h += 28
img = np.array(img_pil)

fig=plt.figure(figsize=[12,12])
plt.imshow(img)
plt.axis('off')
plt.show()
#cv2.imwrite("zodiac.png", img)
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
Cell [0;32mIn[2], line 15[0m
[1;32m     13[0m draw [38;5;241m=[39m ImageDraw[38;5;241m.[39mDraw(img_pil)
[1;32m     14[0m h[38;5;241m=[39m[38;5;241m100[39m [38;5;66;03m# 文字を描き始める最初の高さ[39;00m
[0;32m---> 15[0m [38;5;28;01mfor[39;00m i [38;5;129;01min[39;00m fullfontcode[38;5;241m.[39msplit([38;5;124m"[39m[38;5;130;01m\n[39;00m[38;5;124m"[39m):
[1;32m     16[0m 	draw[38;5;241m.[39mtext(([38;5;241m50[39m, h), i[38;5;241m.[39mstrip(), font [38;5;241m=[39m font, fill [38;5;241m=[39m (b, g, r, a))
[1;32m     17[0m 	h [38;5;241m+[39m[38;5;241m=[39m [38;5;241m28[39m

[0;31mNameError[0m: name 'fullfontcode' is not defined

