Traceback (most recent call last):
  File "/opt/anaconda3/envs/jupyter-book-py311/lib/python3.11/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/opt/anaconda3/envs/jupyter-book-py311/lib/python3.11/site-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/jupyter-book-py311/lib/python3.11/site-packages/jupyter_core/utils/__init__.py", line 173, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/jupyter-book-py311/lib/python3.11/asyncio/base_events.py", line 654, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/jupyter-book-py311/lib/python3.11/site-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/opt/anaconda3/envs/jupyter-book-py311/lib/python3.11/site-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/opt/anaconda3/envs/jupyter-book-py311/lib/python3.11/site-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# https://github.com/H0j3n/Zodiac-Z340/tree/main

import sys,os,random,re
import numpy as np
from PIL import ImageFont, ImageDraw, Image
import cv2
import time

#Zodiac Character (refer : Dcode)
zodiac = {
	"A" : ["char(79)","char(122)","char(108)","char(42)"],
	"B" : ["char(102)","char(95)"],
	"C" : ["char(112)"],
	"D" : ["char(65)","char(54)","char(83)"],
	"E" : ["char(66)","char(98)","char(78)","char(124)","char(52)","char(99)"],
	"F" : ["char(70)"],
	"G" : ["char(76)"],
	"H" : ["char(43)"],
	"I" : ["char(72)","char(80)","char(60)","char(121)","char(107)"],
	"J" : ["char(33)"],
	"K" : ["char(92)"],
	"L" : ["char(116)","char(100)","char(55)"],
	"M" : ["char(50)"],
	"N" : ["char(46)","char(62)","char(68)","char(89)","char(57)"],
	"O" : ["char(82)","char(94)","char(77)"],
	"P" : ["char(106)","char(56)"],
	"Q" : ["char(61)"],
	"R" : ["char(69)","char(88)","char(84)","char(49)","char(90)"],
	"S" : ["char(38)","char(85)","char(45)","char(74)"],
	"T" : ["char(37)","char(71)","char(35)","char(40)","char(58)"],
	"U" : ["char(113)","char(64)","char(47)"],
	"V" : ["char(53)"],
	"W" : ["char(87)","char(41)"],
	"X" : ["char(101)"],
	"Y" : ["char(67)","char(51)"],
	"Z" : ["char(114)"]
}

#Function Diagnol
def diagnol(x):
	col_1 = x[0] + x[9] + x[18] + x[27] + x[36] + x[45] + x[54] + x[63] + x[72] + x[81] + x[90] + x[99] + x[108] + x[117] + x[126] + x[135] + x[144]
	col_2 = x[136] + x[145] + x[1] + x[10] + x[19] + x[28] + x[37] + x[46] + x[55] + x[64] + x[73] + x[82] + x[91] + x[100] + x[109] + x[118] + x[127]
	col_3 = x[119] + x[128] + x[137] + x[146] + x[2] + x[11] + x[20] + x[29] + x[38] + x[47] + x[56] + x[65] + x[74] + x[83] + x[92] + x[101] + x[110]
	col_4 = x[102] + x[111] + x[120] + x[129] + x[138] + x[147] + x[3] + x[12] + x[21] + x[30] + x[39] + x[48] + x[57] + x[66] + x[75] + x[84] + x[93]
	col_5 = x[85] + x[94] + x[103] + x[112] + x[121] + x[130] + x[139] + x[148] + x[4] + x[13] + x[22] + x[31] + x[40] + x[49] + x[58] + x[67] + x[76]
	col_6 = x[68] + x[77] + x[86] + x[95] + x[104] + x[113] + x[122] + x[131] + x[140] + x[149] + x[5] + x[14] + x[23] + x[32] + x[41] + x[50] + x[59]
	col_7 = x[51] + x[60] + x[69] + x[78] + x[87] + x[96] + x[105] + x[114] + x[123] + x[132] + x[141] + x[150] + x[6] + x[15] + x[24] + x[33] + x[42]
	col_8 = x[34] + x[43] + x[52] + x[61] + x[70] + x[79] + x[88] + x[97] + x[106] + x[115] + x[124] + x[133] + x[142] + x[151] + x[7] + x[16] + x[25]
	col_9 = x[17] + x[26] + x[35] + x[44] + x[53] + x[62] + x[71] + x[80] + x[89] + x[98] + x[107] + x[116] + x[125] + x[134] + x[143] + x[152] + x[8]
	return col_1+";"+col_2+";"+col_3+";"+col_4+";"+col_5+";"+col_6+";"+col_7+";"+col_8+";"+col_9

#Function Dcode Symbol
def zodiac_cipher(x):
	#print("\nPlease Enter this in Dcode!\n")
	strs =""
	for i in x.split(";"):
        	for j in i:
                	if j in zodiac.keys():
                        	strs += random.choice(zodiac[j])
                	else:
                        	strs += j
        	strs += "\n"
	return strs

#Function Font Changes
def font_change(x):
	strs =""
	for i in x.split("\n")[:-1]:
		temp = i.replace(")",";").replace("char(",";").replace(";;",";")
		for j in temp.split(";"):
			try:	
				if int(j) in [1,2,3,4,5,6,7,8,9,0]:
					strs += j
				else:
					strs += chr(int(j))
			except:
				strs += j
		strs += "\n"
	return strs
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mImportError[0m                               Traceback (most recent call last)
Cell [0;32mIn[1], line 5[0m
[1;32m      3[0m [38;5;28;01mimport[39;00m [38;5;21;01msys[39;00m[38;5;241m,[39m[38;5;21;01mos[39;00m[38;5;241m,[39m[38;5;21;01mrandom[39;00m[38;5;241m,[39m[38;5;21;01mre[39;00m
[1;32m      4[0m [38;5;28;01mimport[39;00m [38;5;21;01mnumpy[39;00m [38;5;28;01mas[39;00m [38;5;21;01mnp[39;00m
[0;32m----> 5[0m [38;5;28;01mfrom[39;00m [38;5;21;01mPIL[39;00m [38;5;28;01mimport[39;00m ImageFont, ImageDraw, Image
[1;32m      6[0m [38;5;28;01mimport[39;00m [38;5;21;01mcv2[39;00m
[1;32m      7[0m [38;5;28;01mimport[39;00m [38;5;21;01mtime[39;00m

File [0;32m/opt/anaconda3/envs/jupyter-book-py311/lib/python3.11/site-packages/PIL/ImageFont.py:35[0m
[1;32m     32[0m [38;5;28;01mfrom[39;00m [38;5;21;01menum[39;00m [38;5;28;01mimport[39;00m IntEnum
[1;32m     33[0m [38;5;28;01mfrom[39;00m [38;5;21;01mio[39;00m [38;5;28;01mimport[39;00m BytesIO
[0;32m---> 35[0m [38;5;28;01mfrom[39;00m [38;5;21;01m.[39;00m [38;5;28;01mimport[39;00m Image
[1;32m     36[0m [38;5;28;01mfrom[39;00m [38;5;21;01m.[39;00m[38;5;21;01m_util[39;00m [38;5;28;01mimport[39;00m is_directory, is_path
[1;32m     39[0m [38;5;28;01mclass[39;00m [38;5;21;01mLayout[39;00m(IntEnum):

File [0;32m/opt/anaconda3/envs/jupyter-book-py311/lib/python3.11/site-packages/PIL/Image.py:82[0m
[1;32m     73[0m MAX_IMAGE_PIXELS [38;5;241m=[39m [38;5;28mint[39m([38;5;241m1024[39m [38;5;241m*[39m [38;5;241m1024[39m [38;5;241m*[39m [38;5;241m1024[39m [38;5;241m/[39m[38;5;241m/[39m [38;5;241m4[39m [38;5;241m/[39m[38;5;241m/[39m [38;5;241m3[39m)
[1;32m     76[0m [38;5;28;01mtry[39;00m:
[1;32m     77[0m     [38;5;66;03m# If the _imaging C module is not present, Pillow will not load.[39;00m
[1;32m     78[0m     [38;5;66;03m# Note that other modules should not refer to _imaging directly;[39;00m
[1;32m     79[0m     [38;5;66;03m# import Image and use the Image.core variable instead.[39;00m
[1;32m     80[0m     [38;5;66;03m# Also note that Image.core is not a publicly documented interface,[39;00m
[1;32m     81[0m     [38;5;66;03m# and should be considered private and subject to change.[39;00m
[0;32m---> 82[0m     [38;5;28;01mfrom[39;00m [38;5;21;01m.[39;00m [38;5;28;01mimport[39;00m _imaging [38;5;28;01mas[39;00m core
[1;32m     84[0m     [38;5;28;01mif[39;00m __version__ [38;5;241m!=[39m [38;5;28mgetattr[39m(core, [38;5;124m"[39m[38;5;124mPILLOW_VERSION[39m[38;5;124m"[39m, [38;5;28;01mNone[39;00m):
[1;32m     85[0m         msg [38;5;241m=[39m (
[1;32m     86[0m             [38;5;124m"[39m[38;5;124mThe _imaging extension was built for another version of Pillow or PIL:[39m[38;5;130;01m\n[39;00m[38;5;124m"[39m
[1;32m     87[0m             [38;5;124mf[39m[38;5;124m"[39m[38;5;124mCore version: [39m[38;5;132;01m{[39;00m[38;5;28mgetattr[39m(core,[38;5;250m [39m[38;5;124m'[39m[38;5;124mPILLOW_VERSION[39m[38;5;124m'[39m,[38;5;250m [39m[38;5;28;01mNone[39;00m)[38;5;132;01m}[39;00m[38;5;130;01m\n[39;00m[38;5;124m"[39m
[1;32m     88[0m             [38;5;124mf[39m[38;5;124m"[39m[38;5;124mPillow version: [39m[38;5;132;01m{[39;00m__version__[38;5;132;01m}[39;00m[38;5;124m"[39m
[1;32m     89[0m         )

[0;31mImportError[0m: dlopen(/opt/anaconda3/envs/jupyter-book-py311/lib/python3.11/site-packages/PIL/_imaging.cpython-311-darwin.so, 0x0002): Library not loaded: @rpath/libtiff.5.dylib
  Referenced from: <DB29B4E0-5E05-3F26-ABC5-79A53D06F310> /opt/anaconda3/envs/jupyter-book-py311/lib/python3.11/site-packages/PIL/_imaging.cpython-311-darwin.so
  Reason: tried: '/opt/anaconda3/envs/jupyter-book-py311/lib/python3.11/site-packages/PIL/../../../libtiff.5.dylib' (no such file), '/opt/anaconda3/envs/jupyter-book-py311/lib/python3.11/site-packages/PIL/../../../libtiff.5.dylib' (no such file), '/opt/anaconda3/envs/jupyter-book-py311/bin/../lib/libtiff.5.dylib' (no such file), '/opt/anaconda3/envs/jupyter-book-py311/bin/../lib/libtiff.5.dylib' (no such file), '/usr/local/lib/libtiff.5.dylib' (no such file), '/usr/lib/libtiff.5.dylib' (no such file, not in dyld cache)

